---

services:
  gemstash:
    image: gemstash:latest
    container_name: gemstash
    ports:
      - 8080:8080
    volumes:
      - ./gemstash-data:/var/gemstash-data
    env_file:
      - .env
    depends_on:
      postgres:
        condition: service_healthy
      memcached:
        condition: service_healthy

  postgres:
    image: postgres:alpine
    pull_policy: always
    container_name: postgres
    env_file:
      - .env
    expose:
      - 5432
    healthcheck:
      test: ["CMD-SHELL", "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}'"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  memcached:
    image: memcached:alpine
    pull_policy: always
    container_name: memcached
    expose:
      - 11211
    healthcheck:
      test: ["CMD-SHELL", "echo 'version' | nc -vn -w 1 127.0.0.1 11211"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s
